export enum CommandTypes {
    access = "access",
    audit = "audit",
    bin = "bin",
    cache = "cache",
    deprecate = "deprecate",
    doctor = "doctor",
    document = "document",
    hook = "hook",
    ignore = "ignore",
    init = "init",
    install = "install",
    login = "login",
    ls = "ls",
    org = "org",
    outdated = "outdated",
    owner = "owner",
    ping = "ping",
}